# Copyright 2019 ZTE Corporation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Generated by Django 1.11.9 on 2019-04-16 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPInstModel',
            fields=[
                ('cpinstanceid', models.CharField(db_column=b'CPINSTANCEID', max_length=255, primary_key=True, serialize=False)),
                ('cpdid', models.CharField(db_column=b'CPDID', max_length=255)),
                ('cpinstancename', models.CharField(db_column=b'CPINSTANCENAME', max_length=255)),
                ('ownertype', models.IntegerField(db_column=b'OWNERTYPE')),
                ('ownerid', models.CharField(db_column=b'OWNERID', max_length=255)),
                ('relatedtype', models.IntegerField(db_column=b'RELATEDTYPE')),
                ('relatedvl', models.CharField(blank=True, db_column=b'RELATEDVL', max_length=255, null=True)),
                ('relatedcp', models.CharField(blank=True, db_column=b'RELATEDCP', max_length=255, null=True)),
                ('relatedport', models.CharField(blank=True, db_column=b'RELATEDPORT', max_length=255, null=True)),
                ('status', models.CharField(db_column=b'STATUS', max_length=255)),
            ],
            options={
                'db_table': 'NFVO_CPINST',
            },
        ),
        migrations.CreateModel(
            name='DefPkgMappingModel',
            fields=[
                ('service_id', models.CharField(db_column=b'serviceId', max_length=255, primary_key=True, serialize=False)),
                ('service_def_id', models.CharField(db_column=b'serviceDefId', max_length=255)),
                ('template_id', models.CharField(db_column=b'templateId', max_length=255)),
                ('template_name', models.CharField(db_column=b'templateName', max_length=255)),
            ],
            options={
                'db_table': 't_lcm_defPackage_mapping',
            },
        ),
        migrations.CreateModel(
            name='FPInstModel',
            fields=[
                ('fpid', models.CharField(db_column=b'FPID', max_length=255)),
                ('fpinstid', models.CharField(db_column=b'FPINSTID', max_length=255, primary_key=True, serialize=False)),
                ('fpname', models.CharField(db_column=b'FPNAME', max_length=255)),
                ('nsinstid', models.CharField(db_column=b'NSINSTID', max_length=255)),
                ('vnffginstid', models.CharField(db_column=b'VNFFGINSTID', max_length=255)),
                ('symmetric', models.IntegerField(db_column=b'SYMMETRIC', null=True)),
                ('policyinfo', models.TextField(db_column=b'POLICYINFO', max_length=65535)),
                ('forworderpaths', models.CharField(blank=True, db_column=b'FORWORDERPATHS', max_length=255, null=True)),
                ('status', models.CharField(db_column=b'STATUS', max_length=255)),
                ('sdncontrollerid', models.CharField(db_column=b'SDNCONTROLLERID', max_length=255)),
                ('sfcid', models.CharField(db_column=b'SFCID', max_length=255)),
                ('flowclassifiers', models.CharField(db_column=b'FLOWCLASSIFIERS', max_length=255)),
                ('portpairgroups', models.TextField(db_column=b'PORTPAIRGROUPS', max_length=65535)),
            ],
            options={
                'db_table': 'NFVO_FPINST',
            },
        ),
        migrations.CreateModel(
            name='InputParamMappingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(db_column=b'serviceId', max_length=255)),
                ('input_key', models.CharField(db_column=b'inputKey', max_length=255)),
                ('input_value', models.CharField(blank=True, db_column=b'inputValue', max_length=255, null=True)),
            ],
            options={
                'db_table': 't_lcm_inputParam_mapping',
            },
        ),
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('jobid', models.CharField(db_column=b'JOBID', max_length=255, primary_key=True, serialize=False)),
                ('jobtype', models.CharField(db_column=b'JOBTYPE', max_length=255)),
                ('jobaction', models.CharField(db_column=b'JOBACTION', max_length=255)),
                ('resid', models.CharField(db_column=b'RESID', max_length=255)),
                ('status', models.IntegerField(blank=True, db_column=b'STATUS', null=True)),
                ('starttime', models.CharField(blank=True, db_column=b'STARTTIME', max_length=255, null=True)),
                ('endtime', models.CharField(blank=True, db_column=b'ENDTIME', max_length=255, null=True)),
                ('progress', models.IntegerField(blank=True, db_column=b'PROGRESS', null=True)),
                ('user', models.CharField(blank=True, db_column=b'USER', max_length=255, null=True)),
                ('parentjobid', models.CharField(blank=True, db_column=b'PARENTJOBID', max_length=255, null=True)),
                ('resname', models.CharField(blank=True, db_column=b'RESNAME', max_length=255, null=True)),
            ],
            options={
                'db_table': 'NFVO_JOB',
            },
        ),
        migrations.CreateModel(
            name='JobStatusModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indexid', models.IntegerField(db_column=b'INDEXID')),
                ('jobid', models.CharField(db_column=b'JOBID', max_length=255)),
                ('status', models.CharField(db_column=b'STATUS', max_length=255)),
                ('progress', models.IntegerField(blank=True, db_column=b'PROGRESS', null=True)),
                ('descp', models.TextField(db_column=b'DESCP', max_length=65535)),
                ('errcode', models.CharField(blank=True, db_column=b'ERRCODE', max_length=255, null=True)),
                ('addtime', models.CharField(blank=True, db_column=b'ADDTIME', max_length=255, null=True)),
            ],
            options={
                'db_table': 'NFVO_JOB_STATUS',
            },
        ),
        migrations.CreateModel(
            name='NfInstModel',
            fields=[
                ('nfinstid', models.CharField(db_column=b'NFINSTID', max_length=200, primary_key=True, serialize=False)),
                ('mnfinstid', models.CharField(blank=True, db_column=b'M_NFINSTID', max_length=200, null=True)),
                ('nf_name', models.CharField(blank=True, db_column=b'NFNAME', max_length=100, null=True)),
                ('template_id', models.CharField(blank=True, db_column=b'TEMPLATEID', max_length=200, null=True)),
                ('vnf_id', models.CharField(blank=True, db_column=b'VNFID', max_length=200, null=True)),
                ('package_id', models.CharField(blank=True, db_column=b'PACKAGEID', max_length=200, null=True)),
                ('vnfm_inst_id', models.CharField(blank=True, db_column=b'VNFMINSTID', max_length=200, null=True)),
                ('ns_inst_id', models.CharField(blank=True, db_column=b'NSINSTID', max_length=200, null=True)),
                ('status', models.CharField(blank=True, db_column=b'STATUS', max_length=20, null=True)),
                ('flavour_id', models.CharField(blank=True, db_column=b'FLAVOURID', max_length=200, null=True)),
                ('vnf_level', models.CharField(blank=True, db_column=b'VNFLEVEL', max_length=200, null=True)),
                ('location', models.CharField(blank=True, db_column=b'LOCATION', max_length=200, null=True)),
                ('max_vm', models.IntegerField(db_column=b'MAXVM', null=True)),
                ('max_cpu', models.IntegerField(db_column=b'MAXCPU', null=True)),
                ('max_ram', models.IntegerField(db_column=b'MAXRAM', null=True)),
                ('max_hd', models.IntegerField(db_column=b'MAXHD', null=True)),
                ('max_shd', models.IntegerField(db_column=b'MAXSHD', null=True)),
                ('max_net', models.IntegerField(db_column=b'MAXNET', null=True)),
                ('version', models.CharField(db_column=b'VERSION', max_length=255, null=True)),
                ('vendor', models.CharField(blank=True, db_column=b'VENDOR', max_length=255, null=True)),
                ('vnfd_model', models.TextField(blank=True, db_column=b'VNFDMODEL', max_length=20000, null=True)),
                ('input_params', models.TextField(blank=True, db_column=b'INPUTPARAMS', max_length=2000, null=True)),
                ('scale_params', models.TextField(blank=True, db_column=b'SCALEPARAMS', max_length=2000, null=True)),
                ('create_time', models.CharField(blank=True, db_column=b'CREATETIME', max_length=200, null=True)),
                ('lastuptime', models.CharField(blank=True, db_column=b'LASTUPTIME', max_length=200, null=True)),
                ('extension', models.TextField(blank=True, db_column=b'EXTENSION', max_length=65535, null=True)),
            ],
            options={
                'db_table': 'NFVO_NFINST',
            },
        ),
        migrations.CreateModel(
            name='NfPackageModel',
            fields=[
                ('uuid', models.CharField(db_column=b'UUID', max_length=255, primary_key=True, serialize=False)),
                ('nfpackageid', models.CharField(db_column=b'NFPACKAGEID', max_length=200)),
                ('vnfdid', models.CharField(db_column=b'VNFDID', max_length=255)),
                ('vendor', models.CharField(db_column=b'VENDOR', max_length=255)),
                ('vnfdversion', models.CharField(db_column=b'VNFDVERSION', max_length=255)),
                ('vnfversion', models.CharField(db_column=b'VNFVERSION', max_length=255)),
                ('vnfdmodel', models.TextField(blank=True, db_column=b'VNFDMODEL', max_length=65535, null=True)),
                ('vnfd_path', models.CharField(blank=True, db_column=b'VNFDPATH', max_length=300, null=True)),
            ],
            options={
                'db_table': 'NFVO_NFPACKAGE',
            },
        ),
        migrations.CreateModel(
            name='NSDModel',
            fields=[
                ('id', models.CharField(db_column=b'ID', max_length=200, primary_key=True, serialize=False)),
                ('nsd_id', models.CharField(db_column=b'NSDID', max_length=200)),
                ('name', models.CharField(db_column=b'NAME', max_length=200)),
                ('vendor', models.CharField(blank=True, db_column=b'VENDOR', max_length=200, null=True)),
                ('description', models.CharField(blank=True, db_column=b'DESCRIPTION', max_length=200, null=True)),
                ('version', models.CharField(blank=True, db_column=b'VERSION', max_length=200, null=True)),
                ('nsd_model', models.TextField(blank=True, db_column=b'NSDMODEL', max_length=65535, null=True)),
                ('nsd_path', models.CharField(blank=True, db_column=b'NSDPATH', max_length=300, null=True)),
            ],
            options={
                'db_table': 'NFVO_NSPACKAGE',
            },
        ),
        migrations.CreateModel(
            name='NSInstModel',
            fields=[
                ('id', models.CharField(db_column=b'ID', max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column=b'NAME', max_length=200)),
                ('nspackage_id', models.CharField(blank=True, db_column=b'NSPACKAGEID', max_length=200, null=True)),
                ('nsd_id', models.CharField(db_column=b'NSDID', max_length=200)),
                ('nsd_invariant_id', models.CharField(db_column=b'NSDINVARIANTID', max_length=200)),
                ('description', models.CharField(blank=True, db_column=b'DESCRIPTION', max_length=255, null=True)),
                ('sdncontroller_id', models.CharField(blank=True, db_column=b'SDNCONTROLLERID', max_length=200, null=True)),
                ('flavour_id', models.CharField(blank=True, db_column=b'FLAVOURID', max_length=200, null=True)),
                ('ns_level', models.CharField(blank=True, db_column=b'NSLEVEL', max_length=200, null=True)),
                ('status', models.CharField(blank=True, db_column=b'STATUS', max_length=200, null=True)),
                ('nsd_model', models.TextField(blank=True, db_column=b'NSDMODEL', max_length=20000, null=True)),
                ('input_params', models.TextField(blank=True, db_column=b'INPUTPARAMS', max_length=2000, null=True)),
                ('scale_params', models.TextField(blank=True, db_column=b'SCALEPARAMS', max_length=2000, null=True)),
                ('create_time', models.CharField(blank=True, db_column=b'CREATETIME', max_length=200, null=True)),
                ('lastuptime', models.CharField(blank=True, db_column=b'LASTUPTIME', max_length=200, null=True)),
                ('global_customer_id', models.CharField(blank=True, db_column=b'GLOBALCUSTOMERID', max_length=50, null=True)),
                ('service_type', models.CharField(blank=True, db_column=b'SERVICETYPE', max_length=50, null=True)),
            ],
            options={
                'db_table': 'NFVO_NSINST',
            },
        ),
        migrations.CreateModel(
            name='NSLcmOpOccModel',
            fields=[
                ('id', models.CharField(db_column=b'ID', max_length=255, primary_key=True, serialize=False)),
                ('operation_state', models.CharField(db_column=b'OPERATIONSTATE', max_length=30)),
                ('state_entered_time', models.CharField(db_column=b'STATEENTEREDTIME', max_length=30)),
                ('start_time', models.CharField(db_column=b'STARTTIME', max_length=30)),
                ('ns_instance_id', models.CharField(db_column=b'NSINSTANCEID', max_length=255)),
                ('operation', models.CharField(db_column=b'OPERATION', max_length=30)),
                ('is_automatic_invocation', models.CharField(db_column=b'ISAUTOMATICINVOCATION', max_length=5)),
                ('operation_params', models.TextField(db_column=b'OPERATIONPARAMS')),
                ('is_cancel_pending', models.CharField(db_column=b'ISCANCELPENDING', max_length=5)),
                ('cancel_mode', models.TextField(db_column=b'CANCELMODE', null=True)),
                ('error', models.TextField(db_column=b'ERROR', null=True)),
                ('resource_changes', models.TextField(db_column=b'RESOURCECHANGES', null=True)),
                ('links', models.TextField(db_column=b'LINKS')),
            ],
            options={
                'db_table': 'NSLCMOPOCCS',
            },
        ),
        migrations.CreateModel(
            name='OOFDataModel',
            fields=[
                ('request_id', models.CharField(db_column=b'REQUESTID', max_length=255)),
                ('transaction_id', models.CharField(db_column=b'TRANSACTIONID', max_length=255)),
                ('request_status', models.CharField(db_column=b'REQUESTSTATUS', max_length=50)),
                ('request_module_name', models.CharField(db_column=b'RESOURCEMODULENAME', max_length=100)),
                ('service_resource_id', models.CharField(db_column=b'SERVICERESOURCEID', max_length=255, primary_key=True, serialize=False)),
                ('vim_id', models.CharField(blank=True, db_column=b'VIMID', max_length=255, null=True)),
                ('cloud_owner', models.CharField(blank=True, db_column=b'CLOUDOWNER', max_length=100, null=True)),
                ('cloud_region_id', models.CharField(blank=True, db_column=b'CLOUDREGIONID', max_length=255, null=True)),
                ('vdu_info', models.TextField(blank=True, db_column=b'VDUINFO', max_length=65535, null=True)),
            ],
            options={
                'db_table': 'NFVO_OOF_DATA',
            },
        ),
        migrations.CreateModel(
            name='PNFInstModel',
            fields=[
                ('pnfId', models.CharField(db_column=b'PNFID', max_length=255, primary_key=True, serialize=False)),
                ('pnfName', models.CharField(db_column=b'PNFNAME', max_length=255)),
                ('pnfdId', models.CharField(db_column=b'PNFDID', max_length=50)),
                ('pnfdInfoId', models.CharField(db_column=b'PNFDINFOID', max_length=100)),
                ('pnfProfileId', models.CharField(db_column=b'PNFPROFILEID', max_length=255)),
                ('cpInfo', models.TextField(blank=True, db_column=b'CPINFO', max_length=255, null=True)),
                ('emsId', models.CharField(db_column=b'EMSID', max_length=255, null=True)),
                ('nsInstances', models.TextField(blank=True, db_column=b'NSINSTANCES', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'NFVO_PNFINST',
            },
        ),
        migrations.CreateModel(
            name='PortInstModel',
            fields=[
                ('portid', models.CharField(db_column=b'PORTID', max_length=255, primary_key=True, serialize=False)),
                ('networkid', models.CharField(db_column=b'NETWORKID', max_length=255)),
                ('subnetworkid', models.CharField(db_column=b'SUBNETWORKID', max_length=255)),
                ('vimid', models.CharField(db_column=b'VIMID', max_length=255)),
                ('resourceid', models.CharField(db_column=b'RESOURCEID', max_length=255)),
                ('name', models.CharField(db_column=b'NAME', max_length=255)),
                ('instid', models.CharField(db_column=b'INSTID', max_length=255)),
                ('cpinstanceid', models.CharField(db_column=b'CPINSTANCEID', max_length=255)),
                ('bandwidth', models.CharField(db_column=b'BANDWIDTH', max_length=255)),
                ('operationalstate', models.CharField(db_column=b'OPERATIONALSTATE', max_length=255)),
                ('ipaddress', models.CharField(db_column=b'IPADDRESS', max_length=255)),
                ('macaddress', models.CharField(db_column=b'MACADDRESS', max_length=255)),
                ('floatipaddress', models.CharField(db_column=b'FLOATIPADDRESS', max_length=255)),
                ('serviceipaddress', models.CharField(db_column=b'SERVICEIPADDRESS', max_length=255)),
                ('typevirtualnic', models.CharField(db_column=b'TYPEVIRTUALNIC', max_length=255)),
                ('sfcencapsulation', models.CharField(db_column=b'SFCENCAPSULATION', max_length=255)),
                ('direction', models.CharField(db_column=b'DIRECTION', max_length=255)),
                ('tenant', models.CharField(db_column=b'TENANT', max_length=255)),
            ],
            options={
                'db_table': 'NFVO_PORTINST',
            },
        ),
        migrations.CreateModel(
            name='ServiceBaseInfoModel',
            fields=[
                ('service_id', models.CharField(db_column=b'serviceId', max_length=255, primary_key=True, serialize=False)),
                ('service_name', models.CharField(db_column=b'serviceName', max_length=255)),
                ('service_type', models.CharField(db_column=b'serviceType', max_length=20)),
                ('description', models.CharField(blank=True, db_column=b'description', max_length=255, null=True)),
                ('active_status', models.CharField(db_column=b'activeStatus', max_length=20)),
                ('status', models.CharField(db_column=b'status', max_length=20)),
                ('creator', models.CharField(db_column=b'creator', max_length=50)),
                ('create_time', models.BigIntegerField(db_column=b'createTime')),
            ],
            options={
                'db_table': 't_lcm_servicebaseinfo',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionModel',
            fields=[
                ('subscription_id', models.CharField(db_column=b'SUBSCRIPTIONID', max_length=255, primary_key=True, serialize=False)),
                ('vnf_instance_filter', models.TextField(db_column=b'VNFINSTANCEFILTER', null=True)),
                ('ns_instance_filter', models.TextField(db_column=b'NSINSTANCEFILTER', null=True)),
                ('notification_types', models.TextField(db_column=b'NOTIFICATIONTYPES', null=True)),
                ('operation_types', models.TextField(db_column=b'OPERATIONTYPES', null=True)),
                ('operation_states', models.TextField(db_column=b'OPERATIONSTATES', null=True)),
                ('ns_component_types', models.TextField(db_column=b'NSCOMPONENTTYPES', null=True)),
                ('lcm_opname_impacting_nscomponent', models.TextField(db_column=b'LCMOPNAMEIMPACTINGNSCOMPONENT', null=True)),
                ('lcm_opoccstatus_impacting_nscomponent', models.TextField(db_column=b'LCMOPOCCSTATUSIMPACTINGNSCOMPONENT', null=True)),
                ('callback_uri', models.CharField(db_column=b'CALLBACKURI', max_length=255)),
                ('links', models.TextField(db_column=b'LINKS', max_length=20000)),
                ('auth_info', models.TextField(blank=True, db_column=b'AUTHINFO', max_length=20000, null=True)),
            ],
            options={
                'db_table': 'NFVO_SUBSCRIPTION',
            },
        ),
        migrations.CreateModel(
            name='VLInstModel',
            fields=[
                ('vlinstanceid', models.CharField(db_column=b'VLINSTANCEID', max_length=255, primary_key=True, serialize=False)),
                ('vldid', models.CharField(db_column=b'VLDID', max_length=255)),
                ('vlinstancename', models.CharField(blank=True, db_column=b'VLINSTANCENAME', max_length=255, null=True)),
                ('ownertype', models.IntegerField(db_column=b'OWNERTYPE')),
                ('ownerid', models.CharField(db_column=b'OWNERID', max_length=255)),
                ('relatednetworkid', models.CharField(blank=True, db_column=b'RELATEDNETWORKID', max_length=255, null=True)),
                ('relatedsubnetworkid', models.CharField(blank=True, db_column=b'RELATEDSUBNETWORKID', max_length=255, null=True)),
                ('vltype', models.IntegerField(db_column=b'VLTYPE', default=0)),
                ('vimid', models.CharField(db_column=b'VIMID', max_length=255)),
                ('tenant', models.CharField(db_column=b'TENANT', max_length=255)),
                ('status', models.CharField(db_column=b'STATUS', max_length=255)),
            ],
            options={
                'db_table': 'NFVO_VLINST',
            },
        ),
        migrations.CreateModel(
            name='VmInstModel',
            fields=[
                ('vmid', models.CharField(db_column=b'VMID', max_length=255, primary_key=True, serialize=False)),
                ('vimid', models.CharField(db_column=b'VIMID', max_length=255)),
                ('resouceid', models.CharField(db_column=b'RESOURCEID', max_length=255)),
                ('insttype', models.IntegerField(db_column=b'INSTTYPE', null=True)),
                ('instid', models.CharField(db_column=b'INSTID', max_length=255, null=True)),
                ('vmname', models.CharField(db_column=b'VMNAME', max_length=255)),
                ('operationalstate', models.IntegerField(db_column=b'OPERATIONALSTATE', default=1)),
                ('zoneid', models.CharField(db_column=b'ZONEID', max_length=255, null=True)),
                ('tenant', models.CharField(db_column=b'TENANT', max_length=255, null=True)),
                ('hostid', models.CharField(db_column=b'HOSTID', max_length=255)),
                ('detailinfo', models.CharField(db_column=b'DETAILINFO', max_length=255, null=True)),
            ],
            options={
                'db_table': 'NFVO_VMINST',
            },
        ),
        migrations.CreateModel(
            name='VNFCInstModel',
            fields=[
                ('vnfcinstanceid', models.CharField(db_column=b'VNFCINSTANCEID', max_length=255, primary_key=True, serialize=False)),
                ('vduid', models.CharField(db_column=b'VDUID', max_length=255)),
                ('nfinstid', models.CharField(db_column=b'NFINSTID', max_length=255)),
                ('vmid', models.CharField(db_column=b'VMID', max_length=255)),
                ('status', models.CharField(db_column=b'STATUS', max_length=255)),
            ],
            options={
                'db_table': 'NFVO_VNFCINST',
            },
        ),
        migrations.CreateModel(
            name='VNFFGInstModel',
            fields=[
                ('vnffgdid', models.CharField(db_column=b'VNFFGDID', max_length=255)),
                ('vnffginstid', models.CharField(db_column=b'VNFFGINSTID', max_length=255, primary_key=True, serialize=False)),
                ('nsinstid', models.CharField(db_column=b'NSINSTID', max_length=255)),
                ('desc', models.CharField(blank=True, db_column=b'DESC', max_length=255, null=True)),
                ('vendor', models.CharField(blank=True, db_column=b'VENDOR', max_length=255, null=True)),
                ('version', models.CharField(blank=True, db_column=b'VERSION', max_length=255, null=True)),
                ('endpointnumber', models.IntegerField(db_column=b'ENDPOINTNUMBER')),
                ('vllist', models.CharField(db_column=b'VLLIST', max_length=1024)),
                ('cplist', models.CharField(db_column=b'CPLIST', max_length=1024)),
                ('vnflist', models.CharField(db_column=b'VNFLIST', max_length=1024)),
                ('fplist', models.CharField(db_column=b'FPLIST', max_length=1024)),
                ('status', models.CharField(db_column=b'STATUS', max_length=255)),
            ],
            options={
                'db_table': 'NFVO_VNFFGINST',
            },
        ),
        migrations.CreateModel(
            name='VnfPackageFileModel',
            fields=[
                ('id', models.AutoField(db_column=b'ID', primary_key=True, serialize=False)),
                ('vnfpid', models.CharField(db_column=b'NFPACKAGEID', max_length=50)),
                ('filename', models.CharField(db_column=b'FILENAME', max_length=100)),
                ('filetype', models.CharField(db_column=b'FILETYPE', max_length=2)),
                ('imageid', models.CharField(db_column=b'IMAGEID', max_length=50)),
                ('vimid', models.CharField(db_column=b'VIMID', max_length=50)),
                ('vimuser', models.CharField(db_column=b'VIMUSER', max_length=50)),
                ('tenant', models.CharField(db_column=b'TENANT', max_length=50)),
                ('purpose', models.CharField(db_column=b'PURPOSE', max_length=1000)),
                ('status', models.CharField(db_column=b'STATUS', max_length=10)),
            ],
            options={
                'db_table': 'NFVO_NFPACKAGEFILE',
            },
        ),
        migrations.CreateModel(
            name='WFPlanModel',
            fields=[
                ('deployed_id', models.CharField(db_column=b'DEPLOYEDID', max_length=255, primary_key=True, serialize=False)),
                ('process_id', models.CharField(db_column=b'PROCESSID', max_length=255)),
                ('status', models.CharField(db_column=b'STATUS', max_length=255)),
                ('message', models.CharField(db_column=b'MESSAGE', max_length=1024)),
                ('plan_name', models.CharField(db_column=b'PLANNAME', max_length=255)),
            ],
            options={
                'db_table': 'NFVO_WF_PLAN',
            },
        ),
    ]
